apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-svc-monitor
  labels:
  {{- range $k, $v := .Values.serviceMonitor.labels }}
    {{ $k }}: {{ $v }}
  {{- end }}
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
